swagger:
  contact:
    name: Anderson Sales
    email: anderson.luiz.sales@gmail.com
  app:
    name: Xy Inc API
    version: 0.0.1
    description: API responsável por gerenciar pontos de interesse.
  base:
    package: br.com.xyinc.xyincapi

spring:
  data:
    mongodb:
      host: db
      port: 27017
      database: xyinc-api